# This is a basic workflow to help you get started with Actions

name: Clean workflow

# Controls when the workflow will run
on:
  workflow_dispatch:
jobs:
  job_one:
    name: delete
    runs-on: Ubuntu-latest
    steps:
      - name: testing
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd ../pub
            unalias rm
            rm -rf cmsc388T-web-template
