name: Deploy workflow

# Controls when the workflow will run
on:
  push:
    branches: [main]
jobs:
  job_one:
    name: Deploy
    runs-on: Ubuntu-latest
    steps:
      - name: testing
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd ../pub/cmsc388T-web-template
            git pull
